CREATE DATABASE IF NOT EXISTS pekekamp;
USE pekekamp;

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROL VARCHAR(20) DEFAULT 'jugador'
);